//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\BD")]
        public string Catalog {
            get {
                return ((string)(this["Catalog"]));
            }
            set {
                this["Catalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ImageCacheCount {
            get {
                return ((int)(this["ImageCacheCount"]));
            }
            set {
                this["ImageCacheCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ImageCacheDuration {
            get {
                return ((int)(this["ImageCacheDuration"]));
            }
            set {
                this["ImageCacheDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDebug {
            get {
                return ((bool)(this["UseDebug"]));
            }
            set {
                this["UseDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.PNG</string>\r\n  <string>.BMP</string>\r\n  <string>.JPG</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection ImageFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImageFilter"]));
            }
            set {
                this["ImageFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.CBR</string>
  <string>.CBZ</string>
  <string>.ZIP</string>
  <string>.ARJ</string>
  <string>.CAB</string>
  <string>.CHM</string>
  <string>.CPIO</string>
  <string>.DEB</string>
  <string>.DMG</string>
  <string>.HFS</string>
  <string>.ISO</string>
  <string>.LZH</string>
  <string>.LZMA</string>
  <string>.MSI</string>
  <string>.NSIS</string>
  <string>.RAR</string>
  <string>.RPM</string>
  <string>.UDF</string>
  <string>.WIM</string>
  <string>.XAR</string>
  <string>.Z</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BookFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BookFilter"]));
            }
            set {
                this["BookFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseAutoFit {
            get {
                return ((int)(this["UseAutoFit"]));
            }
            set {
                this["UseAutoFit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190")]
        public double ExplorerSize {
            get {
                return ((double)(this["ExplorerSize"]));
            }
            set {
                this["ExplorerSize"] = value;
            }
        }
    }
}
